app = "achiever-backend"
primary_region = "sea"

[build]

[env]
SPRING_PROFILES_ACTIVE = "prod"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[checks]
[checks.health]
type = "http"
port = 8080
path = "/api/health"
interval = "30s"
timeout = "5s"

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"